apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: n1
  name: n1
spec:
  containers:
  - image: nginx:1.23
    name: n1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

